# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Build-A-Cell Engineering
email: atg@buildacell.io
description: > # this means to ignore newlines until "baseurl:"
  We're building a cell. Here are the details.
baseurl: "/engineering" # the subpath of your site, e.g. /blog
url: "http://buildacell.io" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: buildacellproj
github_username:  buildacell

# Build settings
markdown: kramdown
theme: jekyll-theme-cayman
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock

# Github settings
repository: buildacell/engineering

# Prose
prose:
  ignore: [
    '.sass-cache',
    '_includes',
    '_layouts',
    '_sass',
    '_site',
    'css',
    'assets',
    '.gitignore',
    'Gemfile',
    'Gemfile.lock',
    '_config.yml',
    'feed.xml'
    ]
  siteurl: "http://buildacell.io/engineering"
  rooturl: "docs"
  media: "images"
  metadata:
    _posts:
      - name: "layout"
        field:
          element: "hidden"
          value: "blog"
      - name: "title"
        field:
          element: "text"
          label: "title"
          placeholder: "Enter a post title here"
      - name: "date"
        field:
          element: "text"
          label: "date"
          value: "CURRENT_DATETIME"
      - name: "tags"
        field:
          element: "multiselect"
          label: "tags"
          placeholder: "Choose Tags"
          options:
            - name: "Minicells"
              value: "minicells"
            - name: "CRISPRi"
              value: "crispri"
            - name: "Computational Tools"
              value: "comptools"
